import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Navbar1 from "../components/Navbar1";

export const metadata: Metadata = {
  title: "Generatify",
  description: "Generated by Abdullah",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar1 />
          {children}
        </Providers>
      </body>
    </html>
  );
}
